apiVersion: v1
kind: Pod
metadata:
  labels:
    run: collect-data
  name: collect-data
spec:
  containers:
  - image: franckcussac/collect-data-spark-benchmark:1
    name: collect-data
    envFrom:
      - secretRef:
          name: scaleway-credentials
  dnsPolicy: ClusterFirst
  restartPolicy: Always
